# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.peterprovost.org/
title: Peter Provost's Geek Noise
subtitle: Rants, rambles, news and notes from another geek
author: Peter Provost
# simple_search: http://bing.com/search
description: The personal blog of Peter Provost, agilist, hacker, musician, father and Microsoft Program Manager

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
# date_format: "ordinal"
date_format: "%A, %B %d, %Y @ %I:%M %p"  # "Wednesday, April 11, 2012 @ 11:49 PM"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/GeekNoise
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ---------------------------- #
#    Lake Quincy Media Tags    #
# ---------------------------- #
lqm_tags: [ "Visual Studio", "C#", ".NET", "Agile", "Scrum", "Lean", "Cloud", "Hosting", "HTML5", "JavaScript", "Microsoft" ]

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
tag_dir: blog/tags
markdown: kramdown
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Continue reading &raquo;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
# default_asides: [asides/recent_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
default_asides: [custom/asides/about.html, custom/asides/lake_quincy.html, asides/recent_posts.html, asides/tag_cloud.html, asides/twitter.html, custom/asides/sponsors.html, custom/asides/disclaimer.html, custom/asides/license.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: PProvost
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: PProvost
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: peterprovost
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-4907041-1

# Facebook Like
facebook_like: true

